#content.yml
---
- name: list contents of directory in host 
  command: ls /home/ubuntu
  register: contents
- name: check dir is empty
  debug: msg="Directory is empty"
  when: contents.stdout == ""
- name: check dir has contents
  debug: msg="Directory is not empty"
  when: contents.stdout != ""
